#!/bin/sh /etc/rc.common

START=20

REGISTER_ADDR=0xE0040008

start() {
	# Read the value of the register
	echo "Value in register NRST_REG_NRST_2: $(devmem $REGISTER_ADDR)" > /dev/console

	# Reset only bootcount (Bits [7:0])
	CURRENT_VALUE=$(devmem $REGISTER_ADDR)
	NEW_VALUE=$((CURRENT_VALUE & 0xFFFFFF00))
	devmem $REGISTER_ADDR w $NEW_VALUE

	echo "Value in register NRST_REG_NRST_2 after reset: $(devmem $REGISTER_ADDR)" > /dev/console
}