#!/bin/sh
#
# Copyright © 2017 OpenWrt.org
#

. /lib/functions/system.sh
. /lib/functions/uci-defaults.sh

board_config_update

update_interfaces() {
	interfaces=""
	if [ "$1" = "osp-tb341-v2" ]
	then
		device_path="/sys/firmware/devicetree/base/aliases/lan*"
		alias_10g=$(cat sys/firmware/devicetree/base/aliases/10g)
		interfaces="$(cat /sys/firmware/devicetree/base/$alias_10g/label) "
	elif [ "$1" = "osp-tb341" ]
    then
        device_path="/sys/firmware/devicetree/base/aliases/eth[0-6]"
	else
		device_path="/sys/firmware/devicetree/base/aliases/eth*"
	fi
	for eth in $device_path
	do
		if [ -f "$eth" ]
		then
			ethname="$(basename $eth)"
			path=$(cat $eth)
            		if device_type=$(cat /sys/firmware/devicetree/base/$path/device_type 2>/dev/null)
            		then
                		if [ "$device_type" = "network" ]
                		then
                    			label=$(cat /sys/firmware/devicetree/base/$path/label)
                    			if [ -n "$label" ]
					            then
						            interfaces="$interfaces $label"
                    			fi
                		fi
            		fi
        	fi
    	done
	echo "$interfaces"
}


board="$(cat /tmp/sysinfo/board_name)" 2>/dev/null
wan_ifname="$(cat /proc/device-tree/wan/ifname)" 2>/dev/null

case "$board" in
pc-engines-apu|pc-engines-apu2)
	ucidef_set_interfaces_lan_wan "eth1 eth2" "eth0"
	;;
traverse-technologies-geos)
	ucidef_set_interface_lan "eth0 eth1"
	ucidef_add_atm_bridge "0" "35" "llc" "bridged"
	ucidef_set_interface_wan "nas0" "dhcp"
	macaddr="$(cat /sys/class/net/eth0/address)" 2>/dev/null
	[ -n "$macaddr" ] && ucidef_set_interface_macaddr "wan" "$macaddr"
	;;
mxl,lgm|mxl,osp-tb341|mxl,osp-tb341-v2)
	interfaces=$(update_interfaces)
	ucidef_set_interface_lan "$interfaces"
	ucidef_set_interface_wan "$wan_ifname" "dhcp"
	;;

esac
board_config_flush

exit 0
