#!/bin/sh

board="$(cat /proc/device-tree/model)" 2>/dev/null

if [ "$board" = "mxl,lgp" ]; then
        mv /etc/networklayout_lgm.json /etc/networklayout.json

elif [ "$board" = "mxl,osp-tb341" ]; then
        mv /etc/networklayout_ospv1.json /etc/networklayout.json

elif [ "$board" = "mxl,osp-tb341-v2" ]; then
        mv /etc/networklayout_ospv2.json /etc/networklayout.json

elif [ "$board" = "mxl,octopus-641" ] || [ "$board" = "mxl,octopus-851" ]; then
        mv /etc/networklayout_octopus-8vaps.json /etc/networklayout.json

fi

rm -rf /etc/networklayout_*.json

exit 0
